import { z } from "zod";
import { mediaSchema } from "../common/media.schema";

export const updateUserSchema = z.object({
  firstName: z.string(),
  lastName: z.string(),
  email: z.string().email(),
  phoneNumber: z.string().nullable(),
  bio: z.string().nullable(),
  motherTongue: z.string().nullable(),
  dateOfBirth: z.string().nullable(),
  gender: z.string().nullable(),
  nationality: z.string().nullable(),
  country: z.string().nullable(),
  city: z.string().nullable(),
  maritalStatus: z.string().nullable(),
  profilePicture: z.any().optional(),
  additionalPhotos: z.array(z.any()).optional(),
  socialMediaLinks: z
    .array(
      z.object({
        name: z.string(),
        link: z.string().url(),
      })
    )
    .nullable(),
  preferredLanguages: z.array(z.string()).nullable(),
  timeZone: z.string().nullable(),
  highestEducation: z.string().nullable(),
  institutionName: z.string().nullable(),
  profession: z.string().nullable(),
  companyName: z.string().nullable(),
  monthlyIncome: z.number().nullable(),
  incomeCurrency: z.string().nullable(),
  religion: z.string().nullable(),
  politicalView: z.string().nullable(),
  livingArrangement: z.string().nullable(),
  familyMemberCount: z.number().nullable(),
  interestedInGender: z.string().nullable(),
  lookingFor: z.string().nullable(),
  preferredAgeRange: z.string().nullable(),
  preferredNationality: z.array(z.string()).nullable(),
  religionPreference: z.string().nullable(),
  partnerExpectations: z.string().nullable(),
  weightKg: z.number().nullable(),
  heightCm: z.number().nullable(),
  bodyType: z.string().nullable(),
  drinkingHabit: z.string().nullable(),
  smokingHabit: z.string().nullable(),
  healthCondition: z.string().nullable(),
  hasPet: z.boolean().nullable(),
  dietaryPreference: z.string().nullable(),
  children: z.number().nullable(),
  familyBackground: z.string().nullable(),
  culturalPractices: z.string().nullable(),
  astrologicalSign: z.string().nullable(),
  loveLanguage: z.string().nullable(),
  favoriteQuote: z.string().nullable(),
  profileVisibility: z.string(),
  photoVisibility: z.string(),
  messageAvailability: z.string(),
});

export type UpdateUserType = z.infer<typeof updateUserSchema>;

export const updateUserResponseSchema = z.object({
  status: z.number(),
  success: z.boolean(),
  message: z.string(),
  data: z.object({
    id: z.string().uuid(),
    firstName: z.string(),
    lastName: z.string(),
    email: z.string().email(),
    phoneNumber: z.string(),
    bio: z.string(),
    motherTongue: z.string(),
    dateOfBirth: z.string(),
    gender: z.string(),
    nationality: z.string(),
    country: z.string(),
    city: z.string(),
    maritalStatus: z.string(),
    profilePicture: mediaSchema.optional().nullable(),
    additionalPhotos: z.array(mediaSchema).default([]),
    blockedUsers: z.array(z.string()).nullable(),
    likedUsers: z.array(z.string()).nullable(),
    socialMediaLinks: z
      .array(
        z.object({
          name: z.string(),
          link: z.string().url(),
        })
      )
      .nullable(),
    preferredLanguages: z.array(z.string()).default([]),
    userRole: z.string(),
    accountStatus: z.string(),
    purchasedMembership: z
      .object({
        id: z.string(),
        user: z.string(),
        amount: z.string(),
        discount: z.string(),
        payable: z.string(),
        status: z.string(),
        paymentStatus: z.string(),
        purchasedAt: z.string(),
        expiresAt: z.string().nullable(),
        membershipPackageInfo: z.object({
          id: z.number(),
          title: z.string(),
          description: z.array(z.string()),
          categoryInfo: z.object({
            category: z.string(),
            originalPrice: z.number(),
            sellPrice: z.number(),
          }),
        }),
      })
      .nullable(),
    timeZone: z.string(),
    highestEducation: z.string(),
    institutionName: z.string(),
    profession: z.string(),
    companyName: z.string(),
    monthlyIncome: z.number(),
    incomeCurrency: z.string(),
    religion: z.string(),
    politicalView: z.string(),
    livingArrangement: z.string(),
    familyMemberCount: z.number().nullable(),
    interestedInGender: z.string(),
    lookingFor: z.string(),
    preferredAgeRange: z.string(),
    preferredNationality: z.array(z.string()),
    religionPreference: z.string(),
    partnerExpectations: z.string(),
    weightKg: z.number(),
    heightCm: z.number(),
    bodyType: z.string(),
    drinkingHabit: z.string(),
    smokingHabit: z.string(),
    healthCondition: z.string(),
    hasPet: z.boolean().nullable(),
    dietaryPreference: z.string(),
    children: z.number(),
    familyBackground: z.string(),
    culturalPractices: z.string(),
    astrologicalSign: z.string(),
    loveLanguage: z.string(),
    favoriteQuote: z.string(),
    profileVisibility: z.string(),
    photoVisibility: z.string(),
    messageAvailability: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
});

export type UpdateUserResponseType = z.infer<
  typeof updateUserResponseSchema.shape.data
>;
