import { Media } from "../common/common.types";
import { PurchasedMembership } from "../membership/ms-purchase.types";

export interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string | null;
  bio: string | null;
  motherTongue: string | null;
  dateOfBirth: string | null;
  gender: string | null;
  nationality: string | null;
  country: string | null;
  city: string | null;
  maritalStatus: string | null;
  profilePicture: Media | null;
  additionalPhotos: Media[];
  blockedUsers: string[] | null;
  likedUsers: string[] | null;
  socialMediaLinks: Array<{
    name: string;
    link: string;
  }> | null;
  preferredLanguages: string[] | null;
  userRole: "user" | "admin";
  accountStatus: string;
  purchasedMembership: PurchasedMembership | null;
  timeZone: string | null;
  highestEducation: string | null;
  institutionName: string | null;
  profession: string | null;
  companyName: string | null;
  monthlyIncome: number | null;
  incomeCurrency: string | null;
  religion: string | null;
  politicalView: string | null;
  livingArrangement: string | null;
  familyMemberCount: number | null;
  interestedInGender: string | null;
  lookingFor: string | null;
  preferredAgeRange: string | null;
  preferredNationality: string[] | null;
  religionPreference: string | null;
  politicalPreference: string | null;
  partnerExpectations: string | null;
  weightKg: number | null;
  heightCm: number | null;
  bodyType: string | null;
  drinkingHabit: string | null;
  smokingHabit: string | null;
  healthCondition: string | null;
  hasPet: boolean | null;
  dietaryPreference: string | null;
  children: number | null;
  familyBackground: string | null;
  culturalPractices: string | null;
  astrologicalSign: string | null;
  loveLanguage: string | null;
  favoriteQuote: string | null;
  profileVisibility?: boolean;
  photoVisibility?: boolean;
  messageAvailability?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
